export const Auth = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGNOUT_FAIL: 'SIGNOUT_FAIL',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAIL: 'SIGNUP_FAIL',
	REQUEST_AUTH: 'REQUEST_AUTH',
	AUTH_ERROR: 'AUTH_ERROR',
}

export const Profile = {
	REQUEST_GET_PROFILE: 'REQUEST_GET_PROFILE',
	GET_PROFILE: 'GET_PROFILE',
	REQUEST_UPDATE_PROFILE: 'REQUEST_UPDATE_PROFILE',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	PROFILE_ERROR: 'PROFILE_ERROR',
}

export const Category = {
	REQUEST_CATEGORY: 'REQUEST_CATEGORY',
	GET_LIST_CATEGORY: 'GET_LIST_CATEGORY',
	CATEGORY_ERROR: 'CATEGORY_ERROR',
}

export const Blog = {
	REQUEST_GET_LIST_BLOG: 'REQUEST_GET_LIST_BLOG',
	GET_LIST_BLOG: 'GET_LIST_BLOG',
	REQUEST_GET_LIST_BLOG_BY_CATEGORY: 'REQUEST_GET_LIST_BLOG_BY_CATEGORY',
	GET_LIST_BLOG_BY_CATEGORY: 'GET_LIST_BLOG_BY_CATEGORY',
	REQUEST_POST_BLOG: 'REQUEST_POST_BLOG',
	POST_BLOG: 'POST_BLOG',
	REQUEST_UPDATE_BLOG: 'REQUEST_UPDATE_BLOG',
	UPDATE_BLOG: 'UPDATE_BLOG',
	REQUEST_DELETE_BLOG: 'REQUEST_DELETE_BLOG',
	DELETE_BLOG: 'DELETE_BLOG',
	BLOG_ERROR: 'BLOG_ERROR',
}
