export const Auth = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGNOUT_FAIL: 'SIGNOUT_FAIL',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAIL: 'SIGNUP_FAIL',
	REQUEST_AUTH: 'REQUEST_AUTH',
}

export const User = {
	REQUEST_USER_DATA: 'REQUEST_USER_DATA',
	RECEIVE_USER_DATA: 'RECEIVE_USER_DATA',
	RESPONSE_USER_DATA_FAIL: 'RESPONSE_USER_DATA_FAIL',
}

export const Category = {
	REQUEST_LIST_CATEGORY_DATA: 'REQUEST_LIST_CATEGORY_DATA',
	RECEIVE_LIST_CATEGORY_DATA: 'RECEIVE_LIST_CATEGORY_DATA',
	RESPONSE_LIST_CATEGORY_DATA_FAIL: 'RESPONSE_LIST_CATEGORY_DATA_FAIL',
}
