export const Auth = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGNOUT_FAIL: 'SIGNOUT_FAIL',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAIL: 'SIGNUP_FAIL',
	REQUEST_AUTH: 'REQUEST_AUTH',
	RECEIVE_AUTH_DATA: 'RECEIVE_AUTH_DATA',
	REQUEST_SIGN: 'REQUEST_SIGN',
	INITIALIZED_AUTH_DATA: 'INITIALIZED_AUTH_DATA',
}

export const User = {
	REQUEST_USER_DATA: 'REQUEST_USER_DATA',
	RECEIVE_USER_DATA: 'RECEIVE_USER_DATA',
	INITAILIZED_USER_DATA: 'INITIALIZED_USER_DATA',
	FAILED_REQUEST_USER_DATA: 'FAILED_REQUEST_USER_DATA',
}
