export const Auth = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGNOUT_FAIL: 'SIGNOUT_FAIL',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAIL: 'SIGNUP_FAIL',
	REQUEST_AUTH: 'REQUEST_SIGN',
	RECEIVE_AUTH_DATA: 'RECEIVE_AUTH_DATA',
	REQUEST_SIGN: 'REQUEST_SIGN',
}
